(**************************************************************************)
(*                                                                        *)
(*                                 OCaml                                  *)
(*                                                                        *)
(*             Xavier Leroy, projet Cristal, INRIA Rocquencourt           *)
(*                    Mark Shinwell, Jane Street Europe                   *)
(*                                                                        *)
(*   Copyright 1996 Institut National de Recherche en Informatique et     *)
(*     en Automatique.                                                    *)
(*   Copyright 2026 Jane Street Group LLC                                 *)
(*                                                                        *)
(*   All rights reserved.  This file is distributed under the terms of    *)
(*   the GNU Lesser General Public License version 2.1, with the          *)
(*   special exception on linking described in the file LICENSE.          *)
(*                                                                        *)
(**************************************************************************)

[@@@ocaml.warning "+a-40-41-42"]

(* CR gyorsh/mshinwell: This pass needs fixing for register availability set
   propagation *)

open! Int_replace_polymorphic_compare
open Linear

module Make (T : Branch_relaxation_intf.S) = struct
  let label_map code sizes =
    let map = Hashtbl.create 37 in
    let rec fill_map pc instr sizes =
      match instr.desc with
      | Lend -> pc, map
      | Llabel { label = lbl; _ } ->
        Hashtbl.add map lbl pc;
        fill_map pc instr.next (List.tl sizes)
      | Lprologue | Lepilogue_open | Lepilogue_close | Lreloadretaddr | Lreturn
      | Lentertrap | Lpoptrap _ | Lop _ | Lcall_op _ | Lbranch _
      | Lcondbranch (_, _)
      | Lcondbranch3 (_, _, _)
      | Lswitch _ | Ladjust_stack_offset _ | Lpushtrap _ | Lraise _
      | Lstackcheck _ ->
        let { Branch_relaxation_intf.size; _ } = List.hd sizes in
        fill_map (pc + size) instr.next (List.tl sizes)
    in
    fill_map 0 code sizes

  let branch_overflows map pc_branch lbl_dest max_branch_offset =
    let pc_dest = Hashtbl.find map lbl_dest in
    let delta = pc_dest - (pc_branch + T.offset_pc_at_branch) in
    delta <= -max_branch_offset || delta >= max_branch_offset

  let opt_branch_overflows map pc_branch opt_lbl_dest max_branch_offset =
    match opt_lbl_dest with
    | None -> false
    | Some lbl_dest -> branch_overflows map pc_branch lbl_dest max_branch_offset

  let instr_overflows ~code_size ~max_out_of_line_code_offset instr
      max_displacement map pc =
    match max_displacement with
    | None -> false
    | Some displacement -> (
      let max_branch_offset =
        (* Remember to cut some slack for multi-word instructions (in the
           [Linear] sense of the word) where the branch can be anywhere in the
           middle. 12 words of slack is plenty. *)
        displacement - 12
      in
      match instr.desc with
      | Lop (Alloc _) | Lop Poll | Lop (Specific _) | Lstackcheck _ ->
        (* We assume that any branches eligible for relaxation generated by
           these instructions only branch forward. We further assume that any of
           these may branch to an out-of-line code block. *)
        code_size + max_out_of_line_code_offset - pc >= max_branch_offset
      | Lcondbranch (_, lbl) -> branch_overflows map pc lbl max_branch_offset
      | Lcondbranch3 (lbl0, lbl1, lbl2) ->
        opt_branch_overflows map pc lbl0 max_branch_offset
        || opt_branch_overflows map pc lbl1 max_branch_offset
        || opt_branch_overflows map pc lbl2 max_branch_offset
      | Lop
          ( Move | Spill | Reload | Opaque | Pause | Begin_region | End_region
          | Dls_get | Tls_get | Domain_index | Const_int _ | Const_float32 _
          | Const_float _ | Const_symbol _ | Const_vec128 _ | Const_vec256 _
          | Const_vec512 _ | Stackoffset _ | Load _
          | Store (_, _, _)
          | Intop _ | Int128op _
          | Intop_imm (_, _)
          | Intop_atomic _
          | Floatop (_, _)
          | Csel _ | Reinterpret_cast _ | Static_cast _ | Probe_is_enabled _
          | Name_for_debugger _ | Source_location )
      | Lprologue | Lepilogue_open | Lepilogue_close | Lend | Lreloadretaddr
      | Lreturn | Lentertrap | Lpoptrap _ | Lcall_op _ | Llabel _ | Lbranch _
      | Lswitch _ | Ladjust_stack_offset _ | Lpushtrap _ | Lraise _ ->
        Misc.fatal_error "Unsupported instruction for branch relaxation")

  let fixup_branches ~code_size ~max_out_of_line_code_offset map code sizes =
    let expand_optbranch lbl n arg next =
      match lbl with
      | None -> next
      | Some l ->
        let ri = T.relax_condbranch (Iinttest_imm (Ceq, n)) l ~arg in
        instr_cons
          (T.relaxed_instruction_desc ri)
          arg [||] next ~available_before:Reg_availability_set.Unreachable
          ~available_across:Reg_availability_set.Unreachable
    in
    let rec fixup did_fix pc instr sizes =
      match instr.desc with
      | Lend -> did_fix, []
      | Lprologue | Lepilogue_open | Lepilogue_close | Lreloadretaddr | Lreturn
      | Lentertrap | Lpoptrap _ | Lop _ | Lcall_op _ | Llabel _ | Lbranch _
      | Lcondbranch (_, _)
      | Lcondbranch3 (_, _, _)
      | Lswitch _ | Ladjust_stack_offset _ | Lpushtrap _ | Lraise _
      | Lstackcheck _ -> (
        let ({ size; max_displacement }
              : Branch_relaxation_intf.instruction_size) =
          List.hd sizes
        in
        let rest = List.tl sizes in
        let overflows =
          instr_overflows ~code_size ~max_out_of_line_code_offset instr
            max_displacement map pc
        in
        if not overflows
        then
          let did_fix, rest_sizes = fixup did_fix (pc + size) instr.next rest in
          ( did_fix,
            { Branch_relaxation_intf.size; max_displacement } :: rest_sizes )
        else
          let relax_instr ri =
            instr.desc <- T.relaxed_instruction_desc ri;
            let new_size = T.relaxed_instruction_size ri in
            let did_fix, rest_sizes =
              fixup true (pc + new_size.size) instr.next rest
            in
            did_fix, new_size :: rest_sizes
          in
          match instr.desc with
          | Lop Poll -> relax_instr (T.relax_poll ())
          | Lop (Alloc { bytes = num_bytes; dbginfo; _ }) ->
            relax_instr
              (T.relax_allocation ~num_bytes ~dbginfo ~res:instr.res.(0))
          | Lcondbranch (test, lbl) ->
            let lbl2 = Cmm.new_label () in
            let llabel = Llabel { label = lbl2; section_name = None } in
            let ri_branch = T.relax_branch lbl in
            let branch_instr =
              instr_cons
                (T.relaxed_instruction_desc ri_branch)
                [||] [||]
                (instr_cons llabel [||] [||] instr.next
                   ~available_before:Reg_availability_set.Unreachable
                   ~available_across:Reg_availability_set.Unreachable)
                ~available_before:Reg_availability_set.Unreachable
                ~available_across:Reg_availability_set.Unreachable
            in
            let ri_inverted =
              T.relax_condbranch
                (Operation.invert_test test)
                lbl2 ~arg:instr.arg
            in
            instr.desc <- T.relaxed_instruction_desc ri_inverted;
            instr.next <- branch_instr;
            let inverted_size = T.relaxed_instruction_size ri_inverted in
            let branch_size = T.relaxed_instruction_size ri_branch in
            let label_size : Branch_relaxation_intf.instruction_size =
              { size = 0; max_displacement = None }
            in
            let did_fix, rest_sizes =
              fixup true (pc + inverted_size.size) instr.next
                (branch_size :: label_size :: rest)
            in
            did_fix, inverted_size :: rest_sizes
          | Lcondbranch3 (lbl0, lbl1, lbl2) ->
            let original_next = instr.next in
            let cont =
              expand_optbranch lbl0 0 instr.arg
                (expand_optbranch lbl1 1 instr.arg
                   (expand_optbranch lbl2 2 instr.arg original_next))
            in
            instr.desc <- cont.desc;
            instr.next <- cont.next;
            let rec measure_expanded i sizes =
              (* As per comment in linear.ml, we rely on physical equality being
                 precise here, which is ok because values of type
                 [Linear.instruction] are mutable. *)
              if i == original_next
              then sizes
              else
                let ri =
                  match i.desc with
                  | Lcondbranch (test, lbl) ->
                    T.relax_condbranch test lbl ~arg:i.arg
                  | Lprologue | Lepilogue_open | Lepilogue_close | Lend
                  | Lreloadretaddr | Lreturn | Lentertrap | Lpoptrap _ | Lop _
                  | Lcall_op _ | Llabel _ | Lbranch _ | Lcondbranch3 _
                  | Lswitch _ | Ladjust_stack_offset _ | Lpushtrap _ | Lraise _
                  | Lstackcheck _ ->
                    assert false
                in
                let s = T.relaxed_instruction_size ri in
                measure_expanded i.next (s :: sizes)
            in
            let new_sizes = List.rev (measure_expanded instr []) @ rest in
            fixup true pc instr new_sizes
          | Lprologue | Lepilogue_open | Lepilogue_close | Lend | Lreloadretaddr
          | Lreturn | Lentertrap | Lpoptrap _ | Lcall_op _ | Llabel _
          | Lbranch _ | Lswitch _ | Ladjust_stack_offset _ | Lpushtrap _
          | Lraise _ | Lstackcheck _
          | Lop
              ( Move | Spill | Reload | Opaque | Pause | Begin_region
              | End_region | Dls_get | Tls_get | Domain_index | Const_int _
              | Const_float32 _ | Const_float _ | Const_symbol _
              | Const_vec128 _ | Const_vec256 _ | Const_vec512 _ | Stackoffset _
              | Load _
              | Store (_, _, _)
              | Intop _ | Int128op _
              | Intop_imm (_, _)
              | Intop_atomic _
              | Floatop (_, _)
              | Csel _ | Reinterpret_cast _ | Static_cast _ | Probe_is_enabled _
              | Name_for_debugger _ | Source_location | Specific _ ) ->
            (* Any other instruction has already been rejected in
               [instr_overflows] above. We can *never* get here. *)
            assert false)
    in
    fixup false 0 code sizes

  (* Iterate branch expansion till all conditional branches are OK *)

  let max_out_of_line_code_offset block_sizes =
    (* This doesn't count the size of the last block because it needs to return
       the offset to the _start_ of that block. *)
    match List.rev block_sizes with
    | [] | [_] -> 0
    | _last :: rest -> List.fold_left ( + ) 0 rest

  let relax code ~initial_sizes ~out_of_line_code_block_sizes =
    let max_out_of_line_code_offset =
      max_out_of_line_code_offset out_of_line_code_block_sizes
    in
    let min_of_max_branch_offsets =
      List.fold_left
        (fun acc
             ({ max_displacement; _ } : Branch_relaxation_intf.instruction_size)
           -> match max_displacement with None -> acc | Some d -> min acc d)
        max_int initial_sizes
    in
    let rec loop sizes =
      let code_size, map = label_map code sizes in
      if code_size >= min_of_max_branch_offsets
      then
        let did_fix, new_sizes =
          fixup_branches ~code_size ~max_out_of_line_code_offset map code sizes
        in
        if did_fix then loop new_sizes
    in
    loop initial_sizes
end
